"""An offline discovery agent for the shared AgentQA harness domain.

Dream-RSI works on ANY :class:`rsi.core.Domain`: :class:`rsi.dream.DomainTask` scores a
harness by its mean evolve-split score with the frozen task model (``SimModel``
offline). This module supplies a deterministic *discovery agent* for that domain -
each attempt edits the parent's harness by one mechanism (the branch direction):

* ``format``  - ask for a final ``ANSWER: <value>`` line and extract it;
* ``reason``  - ask the model to think step by step (more tokens, more accuracy);
* ``verify``  - ask the model to double-check;
* ``tool``    - have the model write Python, run it with ``tools.python`` and report
  the output (the strongest generic skill under ``SimModel``);
* ``simplify``- drop one previously added mechanism (sometimes harmful).

The harness is regenerated from a small knob set, so every attempt is a real code/
prompt edit that the locked grader scores.
"""
from __future__ import annotations

import ast
import random
from typing import Optional

from ...core.artifact import Artifact
from ...dream.agent import AttemptContext, ParametricAgent

MECHANISMS = ("format", "reason", "verify", "tool", "simplify")

HARNESS = '''"""Harness (generated by the discovery agent from its mechanism knobs)."""
import re

KNOBS = __KNOBS__


def _code(reply):
    m = re.findall(r"```(?:python)?\\n(.*?)```", reply, re.S)
    return m[-1] if m else None


def _answer(reply):
    m = re.findall(r"ANSWER\\s*[:=]\\s*(.+)", reply)
    if m:
        return "ANSWER: " + m[-1].strip()
    lines = [l for l in reply.strip().splitlines() if l.strip()]
    return lines[-1] if lines else ""


def solve(question, llm, tools, files):
    system = files.get("prompts/system.md", "")
    task = files["prompts/task.md"].replace("{question}", question)
    extra = ""
    if KNOBS.get("tool"):
        reply = llm("Write python code that prints the answer to this question.\\n" + question + "\\n```python",
                    system=system)
        code = _code(reply)
        if code:
            out = tools.python(code).strip().splitlines()
            if out:
                extra = "\\nTool output: " + out[-1]
    reply = llm(task + extra, system=system)
    return _answer(reply) if KNOBS.get("format") else (reply.strip().splitlines() or [""])[-1]
'''


def build(knobs: dict) -> Artifact:
    sys_lines = ["You are a helpful assistant."]
    task = "{question}"
    if knobs.get("reason"):
        sys_lines.append("Think step by step before answering.")
    if knobs.get("verify"):
        sys_lines.append("Verify and double-check your answer.")
    if knobs.get("format"):
        task += "\nEnd your reply with a final line of the form 'ANSWER: <value>'."
    k = repr(dict(sorted(knobs.items())))
    return Artifact({"harness.py": HARNESS.replace("__KNOBS__", k), "prompts/system.md": "\n".join(sys_lines) + "\n",
                     "prompts/task.md": task + "\n"})


def read_knobs(art: Artifact) -> dict:
    src = art.get("harness.py", "")
    if "\nKNOBS = " not in src:
        return {}
    try:
        return dict(ast.literal_eval(src.split("\nKNOBS = ", 1)[1].split("\n", 1)[0]))
    except (ValueError, SyntaxError, IndexError):
        return {}


def _mutate(parent: Artifact, rng: random.Random, ctx: Optional[AttemptContext]):
    knobs = read_knobs(parent)
    mech = (ctx.direction.get("direction") if ctx and ctx.direction else None) or rng.choice(MECHANISMS)
    if ctx and ctx.attempt > 0 and rng.random() < 0.3:
        mech = rng.choice(MECHANISMS)
    if mech == "simplify":
        on = sorted(k for k, v in knobs.items() if v)
        if on:
            knobs[rng.choice(on)] = False
    else:
        knobs[mech] = True
    return build(knobs), f"# {mech}\n\nMechanism {mech}; harness knobs now {knobs}."


def agentqa_mock_agent() -> ParametricAgent:
    """Deterministic discovery agent for :class:`rsi.domains.agentqa.AgentQADomain`."""
    return ParametricAgent(_mutate, name="agentqa-mock")
