"""Harness (generated by the discovery agent from its mechanism knobs)."""
import re

KNOBS = {'tool': True}


def _code(reply):
    m = re.findall(r"```(?:python)?\n(.*?)```", reply, re.S)
    return m[-1] if m else None


def _answer(reply):
    m = re.findall(r"ANSWER\s*[:=]\s*(.+)", reply)
    if m:
        return "ANSWER: " + m[-1].strip()
    lines = [l for l in reply.strip().splitlines() if l.strip()]
    return lines[-1] if lines else ""


def solve(question, llm, tools, files):
    system = files.get("prompts/system.md", "")
    task = files["prompts/task.md"].replace("{question}", question)
    extra = ""
    if KNOBS.get("tool"):
        reply = llm("Write python code that prints the answer to this question.\n" + question + "\n```python",
                    system=system)
        code = _code(reply)
        if code:
            out = tools.python(code).strip().splitlines()
            if out:
                extra = "\nTool output: " + out[-1]
    reply = llm(task + extra, system=system)
    return _answer(reply) if KNOBS.get("format") else (reply.strip().splitlines() or [""])[-1]
